// Prices are stored in Tunisian dinars. Source filenames support prototype review.
const category = (id, name, source, rows, note = "") => ({
  id,
  name,
  source,
  note,
  items: rows.map(([name, price, description = ""]) => ({
    name,
    price,
    description,
  })),
});
export const menus = {
  1: {
    name: "SO Restaurant Lounge",
    short: "Le restaurant",
    eyebrow: "À LA TABLE DE SO",
    title: "Le goût des",
    accent: "bons moments.",
    intro: "Des premières bouchées à la dernière note sucrée.",
    theme: "so",
    slug: "restaurant",
    brandLine: "DJERBA · RESTAURANT LOUNGE",
    heroAlt:
      "Les arches éclairées de l’entrée, le soir, sur la salle et le bar.",
    description:
      "La carte de SO Restaurant Lounge : entrées, pâtes, pizzas, poissons, viandes et desserts, avec les prix en dinars tunisiens.",
    categories: [
      category("entrees", "Entrées", "menu1_1.jpg", [
        ["Salade burrata", 35],
        ["Salade César", 32],
        ["Calamar pané", 35],
        ["Scampi crème ail", 45],
      ]),
      category("plats", "Plats", "menu1_1.jpg", [
        ["Cordon bleu", 35],
        ["Short ribs", 52],
        ["Surf & turf", 48],
        ["Côte à l’os", 58],
        ["Filet de bœuf", 55],
        ["Émincé de poulet", 35],
        ["Émincé de bœuf", 48],
      ]),
      category("pates", "Pâtes & risottos", "menu1_1.jpg", [
        ["Spaghetti fruits de mer", 38],
        ["Linguine crevettes", 35],
        ["Linguine à la truffe", 38],
        ["Linguine au saumon", 38],
        ["Linguine carne", 38],
        ["Penne pesto poulet", 35],
        ["Spaghetti bolognaise", 35],
        ["Penne Alfredo", 32],
        ["Lasagne", 32],
        ["Ravioli 4 fromages", 35],
        ["Ravioli viande", 38],
        ["Risotto crevettes", 50],
        ["Risotto pesto burrata", 48],
      ]),
      category("pizzas", "Pizzas", "menu1_1.jpg", [
        ["Margherita", 19, "Sauce tomate, mozzarella, basilic."],
        ["Végétarienne", 23, "Sauce tomate, mozzarella, légumes sautés."],
        [
          "Thon",
          30,
          "Sauce tomate, mozzarella, tomates cerises, thon, olives.",
        ],
        [
          "Calabresi",
          38,
          "Sauce blanche, tomates cerises, mozzarella, poulet, oignon, champignons.",
        ],
        [
          "Diavola",
          32,
          "Sauce tomate, mozzarella, pepperoni, basilic, tomates cerises.",
        ],
        ["Roma", 38, "Sauce blanche, mozzarella, jambon, champignons."],
        [
          "Boursin",
          38,
          "Sauce blanche, mozzarella, Boursin, viande hachée, oignon.",
        ],
        [
          "Truffe",
          38,
          "Sauce blanche, mozzarella, crème de truffe, champignons, roquette.",
        ],
        [
          "4 fromages",
          38,
          "Sauce blanche, mozzarella, fromage fumé, poivre, gorgonzola.",
        ],
        [
          "Pizza SO",
          42,
          "Sauce blanche, mozzarella, pesto, crevettes, basilic, tomates cerises, noix.",
        ],
      ]),
      category("poissons", "Poissons", "menu1_1.jpg", [
        ["Pavé de saumon", 48],
        ["Duo poissons crevettes", 44],
        ["Mezza poisson", 100],
      ]),
      category("desserts", "Desserts", "menu1_1.jpg", [
        ["Fondant chocolat", 20],
        ["Fondant pistache", 20],
        ["Tiramisu", 20],
        ["Cheesecake", 20],
        ["Assiette de fruits", 25],
      ]),
      category("cafes", "Cafés", "menu1_2.jpg", [
        ["Espresso", 6.5],
        ["Capucin", 7],
        ["Café crème", 7.5],
        ["Cappuccino", 8.5],
      ]),
      category("thes", "Thés", "menu1_2.jpg", [
        ["Thé à la menthe", 7],
        ["Thé infusion", 7, "Verveine, rouge ou vert."],
        ["Thé infusion Lipton", 9],
        ["Thé aux amandes", 13.5, "Achak ou fraîches."],
        ["Thé noix de cajou", 14.5],
        ["Thé aux pignons", 15.5],
        ["Thé Chichkhan", 19.5, "Amandes, noix de cajou, pignons."],
      ]),
      category("cocktails", "Cocktails", "menu1_2.jpg", [
        ["Miami", 14.5, "Banane, lait, miel."],
        ["Banana boost", 14.5, "Banane, lait, dattes."],
        ["Arc-en-ciel", 17.5, "Banane, fraise, kiwi."],
        ["Berbère", 17.5, "Pêche, mangue, fraise, banane."],
        ["Hawaï", 17.5, "Banane, orange, ananas."],
        ["Piña colada", 17.5, "Ananas, noix de coco."],
        ["Cocktail fruits secs", 19.5],
        ["Cocktail Chichkhan", 19.5],
        ["Cocktail au choix", 19.5],
      ]),
      category("mojitos", "Mojitos", "menu1_2.jpg", [
        ["Virgin mojito", 14],
        ["Yellow", 15.5, "Pêche."],
        ["Blue", 15.5],
        ["Red", 15.5, "Fraise."],
        ["Fruits des bois", 15.5],
        ["Fruit de la passion", 15.5],
        ["Framboise", 15.5],
        ["Chichkhan", 22, "Red Bull."],
      ]),
      category(
        "sauces",
        "Sauces",
        "menu1_1.jpg",
        [
          ["Crème poivron", 3.5],
          ["Crème champignon", 3.5],
          ["Gorgonzola", 3.5],
        ],
        "En supplément de votre plat.",
      ),
    ],
  },
  2: {
    name: "Chichkhan Café",
    short: "Le café",
    eyebrow: "À L’HEURE CHICHKHAN",
    title: "Un peu, beaucoup,",
    accent: "à partager.",
    intro: "Du premier café aux petites faims qui font durer la journée.",
    theme: "chichkhan",
    slug: "cafe",
    brandLine: "DJERBA · DEPUIS 2002",
    heroAlt:
      "La façade éclairée du Chichkhan Café, le soir, sous son enseigne.",
    description:
      "La carte du Chichkhan Café : petits déjeuners, boissons, crêpes, douceurs et salé, avec les prix en dinars tunisiens.",
    categories: [
      category("petits-dejeuners", "Petits déjeuners", "IMG_2329.jpg", [
        [
          "Classique",
          15.5,
          "Café au choix (express, café crème, capucin ou thé infusion), jus frais (citronnade, fraise ou orange), croissant ou pain au chocolat, eau 0,5 L.",
        ],
        [
          "Benna",
          26.5,
          "Café ou infusion, smoothie au choix (fraise, banane, ananas ou pêche), brioche perdue Nutella caramel, eau 0,5 L.",
        ],
        [
          "Le Gourmand",
          29,
          "Café ou thé infusion, jus frais, granola bowl (yaourt naturel, granola, fruits de saison, miel), crêpe Nutella, assiette charcuterie, fromage, omelettes et croque-monsieur, salade de fruits, confiture, chamia, beurre, eau 0,5 L.",
        ],
        [
          "Le Healthy",
          29.5,
          "Café ou infusion, jus au choix (fraise-pomme, ananas-orange ou pomme-concombre-citron), granola bowl (yaourt naturel, fruits frais, graines de chia, miel), toast d’avocat et œuf mollet, eau 0,5 L.",
        ],
        [
          "Chichkhan",
          56.5,
          "2 cafés ou thés, 2 jus frais, 2 viennoiseries, une assiette sucrée (crêpe, pancake ou gaufre Nutella), beurre, confiture, chamia, bsissa, granola bowl, assiette charcuterie (fromages, omelettes et croissant salé), ojja, eau 1 L.",
        ],
      ]),
      category("cafes", "Cafés & chocolat", "IMG_2330.jpg", [
        ["Expresso", 5],
        ["Café crème", 6],
        ["Capucin", 6.5],
        ["Cappuccino", 7],
        ["Café capsules", 7],
        ["Latte", 7.5],
        ["Chocolat chaud", 7.5],
        ["Café turc", 8],
        ["Chocolat liégeois", 8.5],
        ["Café gourmand", 15],
      ]),
      category("cafes-glaces", "Cafés glacés", "IMG_2330.jpg", [
        ["Frappuccino caramel", 12],
        ["Café glacé", 12.5],
        ["Latte glacé caramel", 12.5],
        ["Café liégeois", 12.5],
        ["Mocha Nutepistache", 13.5],
      ]),
      category("thes", "Thés", "IMG_2330.jpg", [
        ["Thé à la menthe", 6],
        ["Thé infusion", 7],
        ["Thé amande", 12.5],
        ["Thé pignons", 14.5],
        ["Thé gourmand", 15],
        ["Thé Chichkhan", 17],
        [
          "Supplément fruits secs",
          7.5,
          "Pignons, amandes, noix de cajou ou noisettes.",
        ],
        ["Dose Chichkhan", 9.5],
      ]),
      category("jus", "Jus de fruits", "IMG_2330.jpg", [
        ["Citronnade", 12],
        ["Orange", 12],
        ["Citron menthe", 13.5],
        ["Fraise", 13.5],
        ["Citron pressé", 13.5],
        ["Kiwi", 15],
        ["Pastèque", 15],
        ["Melon", 15],
        ["Ananas", 15],
        ["Pêche", 15],
        ["Fraise amande", 16.5],
        ["Citron amande", 16.5],
      ]),
      category("cocktails", "Cocktails", "IMG_2330.jpg", [
        ["Brazilian lemonade", 14.5, "Lait concentré, citronnade."],
        ["Summer drink", 15.5, "Fraise, pastèque, orange, ananas, grenadine."],
        ["Banane boost", 15.5, "Dattes, banane."],
        ["Banane go Dream", 15.5, "Banane, mangue."],
        ["Arc-en-ciel", 15.5, "Banane, kiwi, fraise."],
        ["Berbère", 15.5, "Pêche, menthe, fraise, banane."],
        ["Piña colada", 15.5, "Lait de coco, ananas."],
        ["Exotique", 15.5, "Ananas, mangue, fruit de la passion, kiwi."],
        ["Chichkhane fruits secs", 17.5, "Banane, fruits secs, dattes."],
      ]),
      category("mojitos", "Mojitos", "IMG_2330.jpg", [
        ["Classic", 13.5],
        ["Fraise", 15.5],
        ["Bleu", 15.5],
        ["Framboise", 15.5],
        ["Kiwi", 15.5],
        ["Pastèque", 15.5],
        ["Fruits des bois", 15.5],
        ["Chichkhan", 19.5, "Boisson énergétique, fruit de la passion."],
      ]),
      category("smoothies", "Smoothies", "IMG_2330.jpg", [
        ["Fraise", 14.5],
        ["Bleu", 14.5],
        ["Framboise", 14.5],
        ["Kiwi", 14.5],
        ["Pastèque", 14.5],
        ["Fruits des bois", 14.5],
      ]),
      category("milkshakes", "Milkshakes", "IMG_2330.jpg", [
        ["Classic", 10, "Vanille ou fraise."],
        ["Nutella", 14.5],
        ["Pistache", 14.5],
        ["Spéculoos", 14.5],
        ["Oreo", 14.5],
        ["Kinder", 14.5],
        ["Raffaello", 14.5],
        ["Snickers", 14.5],
        ["Nutella cookie", 14.5],
      ]),
      category("softs", "Boissons fraîches", "IMG_2330.jpg", [
        ["Eau plate 0,5 L", 2.5],
        ["Eau plate 1 L", 4.5],
        ["Eau gazeuse", 4.8],
        ["Soda", 5.5],
        ["Oasis", 6.5],
        ["Énergétique", 10],
      ]),
      category("glaces", "Glaces", "IMG_2330.jpg", [
        ["Boule de glace", 6],
        ["Coupe 3 boules", 13.5],
        ["Sorbet citron", 13.5],
        ["Banane split", 17],
        ["Coupe Chichkhane", 19],
      ]),
      category(
        "crepes-sucrees",
        "Crêpes & gaufres",
        "IMG_2331.jpg",
        [
          ["Sucrée", 12],
          ["Nutella", 14],
          ["Spéculoos", 15],
          ["Nutella banane", 17],
          ["Kinder", 17],
          ["Pistache", 17],
          ["Nutella amande", 18],
          ["Dubaï", 19],
        ],
        "Crêpe, gaufre ou bubble waffle : les mêmes parfums, au choix.",
      ),
      category("brioches", "Brioches perdues", "IMG_2331.jpg", [
        ["Caramel banane", 20],
        ["Kinder Nutella", 20],
        ["Nutella fruits rouges", 23],
      ]),
      category("desserts", "Desserts & douceurs", "IMG_2331.jpg", [
        [
          "Box Le régal de Chichkhan",
          39,
          "Mini crêpe, mini pancake, mini gaufre, fruits frais. Sauces Nutella, pistache, spéculoos et chocolat blanc.",
        ],
        [
          "Gâteaux & douceurs",
          14,
          "Tarte aux fruits, amandes, noix ou pistache.",
        ],
        ["Cheesecake", 14],
        ["Saint-Sébastien", 15],
        ["Tiramisu", 15],
        ["Tiramisu gourmand", 19, "Pistache, noisette ou spéculoos."],
        ["Fondant", 17, "Chocolat ou pistache."],
        ["Assida zgougou", 15],
        ["Assiette de fruits", 25],
      ]),
      category("omelettes", "Omelettes", "IMG_2331.jpg", [
        ["Thon", 12.5],
        ["Thon fromage", 13.5],
        ["Jambon", 13.5],
      ]),
      category("crepes-salees", "Crêpes salées", "IMG_2331.jpg", [
        ["Jambon fromage", 13.5],
        ["Thon fromage", 14.5],
        ["Tunisienne", 15.5, "Thon, harissa, fromage, œuf."],
        ["Norvégienne", 17.5, "Saumon, épinards, fromage."],
        ["Burger", 17.5, "Fromage, œuf, viande hachée."],
        ["Djerbienne", 17.5, "Fromage, poulet, crème."],
      ]),
      category("burgers", "Burgers", "IMG_2333.jpg", [
        ["Classique", 18],
        ["Crispy", 18],
        ["Double cheese", 22],
        ["Bœuf effiloché", 25],
      ]),
      category("panozzos", "Panozzos & tacos", "IMG_2333.jpg", [
        ["Panozzo poulet", 20],
        ["Panozzo viande hachée", 22],
        ["Panozzo bœuf effiloché", 24],
        ["Tacos cordon bleu", 16],
        ["Tacos poulet", 16],
        ["Tacos viande hachée", 18],
        [
          "Box SO Chichkhan",
          42,
          "2 mini panuzzos, tacos, tenders poulet ou cordon bleu, frites ou patates, sauce faite maison.",
        ],
      ]),
      category("pizzas", "Pizzas", "IMG_2333.jpg", [
        ["Margherita", 15, "Sauce tomate, mozzarella, basilic."],
        ["Végétarienne", 16, "Sauce tomate, mozzarella, légumes sautés."],
        ["Roma", 20, "Sauce blanche, mozzarella, jambon, champignons."],
        [
          "Thon",
          22,
          "Sauce tomate, mozzarella, tomates cerises, thon, olives.",
        ],
        [
          "Calabraise",
          22,
          "Sauce blanche, tomates cerises, mozzarella, poulet, oignon, champignons.",
        ],
        [
          "Diavola",
          22,
          "Sauce tomate, mozzarella, pepperoni, basilic, tomates cerises.",
        ],
        [
          "Boursin",
          25,
          "Sauce blanche, mozzarella, Boursin, viande hachée, oignon.",
        ],
        [
          "Truffe",
          28,
          "Sauce blanche, mozzarella, crème de champignon, roquette.",
        ],
        [
          "Fromages",
          28,
          "Sauce blanche, mozzarella, crème de champignon, roquette.",
        ],
        [
          "Pizza SO",
          30,
          "Sauce blanche, mozzarella, pesto, crevettes, basilic, tomates cerises, noix.",
        ],
      ]),
      category(
        "chichas",
        "Chichas",
        "IMG_2332.jpg",
        [
          ["Al Fakher menthe", 18],
          ["Al Fakher pomme", 18],
          ["Al Fakher raisin", 18],
          ["Al Fakher pomme menthe", 18],
          ["Al Fakher raisin menthe", 18],
          ["Al Fakher vanille", 18],
          ["Chicha Chikh", 14],
          ["Chicha Jirak", 16],
          ["Supplément tête chicha", 10],
          ["Adalya Mia Amore", 30],
          ["Adalya Love 66", 30],
          ["Adalya Social Smoke", 30],
          ["Adalya chewing-gum", 30],
          ["Adalya Hawaï", 30],
          ["Adalya melon", 30],
          ["Adalya pastèque", 30],
          ["Adalya menthe sucrée", 30],
        ],
        "Al Fakher : Kaloud, Quasar, Turki ou aluminium.",
      ),
    ],
  },
};
export const normalize = (value) =>
  value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/œ/g, "oe")
    .replace(/['‘’ʼ´`]/g, "");
export const matches = (item, category, query) =>
  normalize(query)
    .trim()
    .split(/\s+/)
    .every((word) =>
      normalize(`${item.name} ${item.description} ${category}`).includes(word),
    );
