-- Chichkhan menu: initial catalogue (73 restaurant items, 150 café items).
-- Run once, after schema.sql. Prices are integer millimes: 15500 = 15,500 DT.
-- Image keys start empty; see the R2 section of README.md to fill them in.
begin;

insert into venues (slug, name, title, subtitle, eyebrow, description, hero_image_alt, hero_focus_y) values
  ('restaurant', 'SO Restaurant Lounge', 'SO', 'Restaurant Lounge', 'Chichkhan Djerba', 'La carte de SO Restaurant Lounge : entrées, pâtes, pizzas, poissons, viandes et desserts, avec les prix en dinars tunisiens.', 'Les arches éclairées de l’entrée, le soir, sur la salle et le bar.', 98),
  ('cafe', 'Chichkhan Café', 'Chichkhan', 'Café', 'Djerba · depuis 2002', 'La carte du Chichkhan Café : petits déjeuners, boissons, crêpes, douceurs et salé, avec les prix en dinars tunisiens.', 'La façade éclairée du Chichkhan Café, le soir, sous son enseigne.', 17);

insert into category_groups (venue, name, position) values
  ('restaurant', 'À table', 1),
  ('restaurant', 'À boire', 2),
  ('restaurant', 'En complément', 3),
  ('cafe', 'Pour commencer', 1),
  ('cafe', 'À boire', 2),
  ('cafe', 'Les douceurs', 3),
  ('cafe', 'Les petites faims', 4),
  ('cafe', 'Chichas', 5);

insert into categories (venue, group_id, slug, name, note, source, position)
select v.venue::venue, g.id, v.slug, v.name, v.note, v.source, v.position
from (values
  ('restaurant', 'À table', 'entrees', 'Entrées', '', 'menu1_1.jpg', 1),
  ('restaurant', 'À table', 'plats', 'Plats', '', 'menu1_1.jpg', 2),
  ('restaurant', 'À table', 'pates', 'Pâtes & risottos', '', 'menu1_1.jpg', 3),
  ('restaurant', 'À table', 'pizzas', 'Pizzas', '', 'menu1_1.jpg', 4),
  ('restaurant', 'À table', 'poissons', 'Poissons', '', 'menu1_1.jpg', 5),
  ('restaurant', 'À table', 'desserts', 'Desserts', '', 'menu1_1.jpg', 6),
  ('restaurant', 'À boire', 'cafes', 'Cafés', '', 'menu1_2.jpg', 7),
  ('restaurant', 'À boire', 'thes', 'Thés', '', 'menu1_2.jpg', 8),
  ('restaurant', 'À boire', 'cocktails', 'Cocktails', '', 'menu1_2.jpg', 9),
  ('restaurant', 'À boire', 'mojitos', 'Mojitos', '', 'menu1_2.jpg', 10),
  ('restaurant', 'En complément', 'sauces', 'Sauces', 'En supplément de votre plat.', 'menu1_1.jpg', 11),
  ('cafe', 'Pour commencer', 'petits-dejeuners', 'Petits déjeuners', '', 'IMG_2329.jpg', 1),
  ('cafe', 'À boire', 'cafes', 'Cafés & chocolat', '', 'IMG_2330.jpg', 2),
  ('cafe', 'À boire', 'cafes-glaces', 'Cafés glacés', '', 'IMG_2330.jpg', 3),
  ('cafe', 'À boire', 'thes', 'Thés', '', 'IMG_2330.jpg', 4),
  ('cafe', 'À boire', 'jus', 'Jus de fruits', '', 'IMG_2330.jpg', 5),
  ('cafe', 'À boire', 'cocktails', 'Cocktails', '', 'IMG_2330.jpg', 6),
  ('cafe', 'À boire', 'mojitos', 'Mojitos', '', 'IMG_2330.jpg', 7),
  ('cafe', 'À boire', 'smoothies', 'Smoothies', '', 'IMG_2330.jpg', 8),
  ('cafe', 'À boire', 'milkshakes', 'Milkshakes', '', 'IMG_2330.jpg', 9),
  ('cafe', 'À boire', 'softs', 'Boissons fraîches', '', 'IMG_2330.jpg', 10),
  ('cafe', 'Les douceurs', 'glaces', 'Glaces', '', 'IMG_2330.jpg', 11),
  ('cafe', 'Les douceurs', 'crepes-sucrees', 'Crêpes & gaufres', 'Crêpe, gaufre ou bubble waffle : les mêmes parfums, au choix.', 'IMG_2331.jpg', 12),
  ('cafe', 'Les douceurs', 'brioches', 'Brioches perdues', '', 'IMG_2331.jpg', 13),
  ('cafe', 'Les douceurs', 'desserts', 'Desserts & douceurs', '', 'IMG_2331.jpg', 14),
  ('cafe', 'Les petites faims', 'omelettes', 'Omelettes', '', 'IMG_2331.jpg', 15),
  ('cafe', 'Les petites faims', 'crepes-salees', 'Crêpes salées', '', 'IMG_2331.jpg', 16),
  ('cafe', 'Les petites faims', 'burgers', 'Burgers', '', 'IMG_2333.jpg', 17),
  ('cafe', 'Les petites faims', 'panozzos', 'Panozzos & tacos', '', 'IMG_2333.jpg', 18),
  ('cafe', 'Les petites faims', 'pizzas', 'Pizzas', '', 'IMG_2333.jpg', 19),
  ('cafe', 'Chichas', 'chichas', 'Chichas', 'Al Fakher : Kaloud, Quasar, Turki ou aluminium.', 'IMG_2332.jpg', 20)
) as v (venue, group_name, slug, name, note, source, position)
join category_groups g on g.venue = v.venue::venue and g.name = v.group_name;

insert into menu_items (venue, category_id, name, description, price_millimes, is_house, position)
select c.venue, c.id, v.name, v.description, v.price_millimes, v.is_house, v.position
from (values
  ('restaurant', 'entrees', 'Salade burrata', '', 35000, false, 1),
  ('restaurant', 'entrees', 'Salade César', '', 32000, false, 2),
  ('restaurant', 'entrees', 'Calamar pané', '', 35000, false, 3),
  ('restaurant', 'entrees', 'Scampi crème ail', '', 45000, false, 4),
  ('restaurant', 'plats', 'Cordon bleu', '', 35000, false, 1),
  ('restaurant', 'plats', 'Short ribs', '', 52000, false, 2),
  ('restaurant', 'plats', 'Surf & turf', '', 48000, false, 3),
  ('restaurant', 'plats', 'Côte à l’os', '', 58000, false, 4),
  ('restaurant', 'plats', 'Filet de bœuf', '', 55000, false, 5),
  ('restaurant', 'plats', 'Émincé de poulet', '', 35000, false, 6),
  ('restaurant', 'plats', 'Émincé de bœuf', '', 48000, false, 7),
  ('restaurant', 'pates', 'Spaghetti fruits de mer', '', 38000, false, 1),
  ('restaurant', 'pates', 'Linguine crevettes', '', 35000, false, 2),
  ('restaurant', 'pates', 'Linguine à la truffe', '', 38000, false, 3),
  ('restaurant', 'pates', 'Linguine au saumon', '', 38000, false, 4),
  ('restaurant', 'pates', 'Linguine carne', '', 38000, false, 5),
  ('restaurant', 'pates', 'Penne pesto poulet', '', 35000, false, 6),
  ('restaurant', 'pates', 'Spaghetti bolognaise', '', 35000, false, 7),
  ('restaurant', 'pates', 'Penne Alfredo', '', 32000, false, 8),
  ('restaurant', 'pates', 'Lasagne', '', 32000, false, 9),
  ('restaurant', 'pates', 'Ravioli 4 fromages', '', 35000, false, 10),
  ('restaurant', 'pates', 'Ravioli viande', '', 38000, false, 11),
  ('restaurant', 'pates', 'Risotto crevettes', '', 50000, false, 12),
  ('restaurant', 'pates', 'Risotto pesto burrata', '', 48000, false, 13),
  ('restaurant', 'pizzas', 'Margherita', 'Sauce tomate, mozzarella, basilic.', 19000, false, 1),
  ('restaurant', 'pizzas', 'Végétarienne', 'Sauce tomate, mozzarella, légumes sautés.', 23000, false, 2),
  ('restaurant', 'pizzas', 'Thon', 'Sauce tomate, mozzarella, tomates cerises, thon, olives.', 30000, false, 3),
  ('restaurant', 'pizzas', 'Calabresi', 'Sauce blanche, tomates cerises, mozzarella, poulet, oignon, champignons.', 38000, false, 4),
  ('restaurant', 'pizzas', 'Diavola', 'Sauce tomate, mozzarella, pepperoni, basilic, tomates cerises.', 32000, false, 5),
  ('restaurant', 'pizzas', 'Roma', 'Sauce blanche, mozzarella, jambon, champignons.', 38000, false, 6),
  ('restaurant', 'pizzas', 'Boursin', 'Sauce blanche, mozzarella, Boursin, viande hachée, oignon.', 38000, false, 7),
  ('restaurant', 'pizzas', 'Truffe', 'Sauce blanche, mozzarella, crème de truffe, champignons, roquette.', 38000, false, 8),
  ('restaurant', 'pizzas', '4 fromages', 'Sauce blanche, mozzarella, fromage fumé, poivre, gorgonzola.', 38000, false, 9),
  ('restaurant', 'pizzas', 'Pizza SO', 'Sauce blanche, mozzarella, pesto, crevettes, basilic, tomates cerises, noix.', 42000, true, 10),
  ('restaurant', 'poissons', 'Pavé de saumon', '', 48000, false, 1),
  ('restaurant', 'poissons', 'Duo poissons crevettes', '', 44000, false, 2),
  ('restaurant', 'poissons', 'Mezza poisson', '', 100000, false, 3),
  ('restaurant', 'desserts', 'Fondant chocolat', '', 20000, false, 1),
  ('restaurant', 'desserts', 'Fondant pistache', '', 20000, false, 2),
  ('restaurant', 'desserts', 'Tiramisu', '', 20000, false, 3),
  ('restaurant', 'desserts', 'Cheesecake', '', 20000, false, 4),
  ('restaurant', 'desserts', 'Assiette de fruits', '', 25000, false, 5),
  ('restaurant', 'cafes', 'Espresso', '', 6500, false, 1),
  ('restaurant', 'cafes', 'Capucin', '', 7000, false, 2),
  ('restaurant', 'cafes', 'Café crème', '', 7500, false, 3),
  ('restaurant', 'cafes', 'Cappuccino', '', 8500, false, 4),
  ('restaurant', 'thes', 'Thé à la menthe', '', 7000, false, 1),
  ('restaurant', 'thes', 'Thé infusion', 'Verveine, rouge ou vert.', 7000, false, 2),
  ('restaurant', 'thes', 'Thé infusion Lipton', '', 9000, false, 3),
  ('restaurant', 'thes', 'Thé aux amandes', 'Achak ou fraîches.', 13500, false, 4),
  ('restaurant', 'thes', 'Thé noix de cajou', '', 14500, false, 5),
  ('restaurant', 'thes', 'Thé aux pignons', '', 15500, false, 6),
  ('restaurant', 'thes', 'Thé Chichkhan', 'Amandes, noix de cajou, pignons.', 19500, true, 7),
  ('restaurant', 'cocktails', 'Miami', 'Banane, lait, miel.', 14500, false, 1),
  ('restaurant', 'cocktails', 'Banana boost', 'Banane, lait, dattes.', 14500, false, 2),
  ('restaurant', 'cocktails', 'Arc-en-ciel', 'Banane, fraise, kiwi.', 17500, false, 3),
  ('restaurant', 'cocktails', 'Berbère', 'Pêche, mangue, fraise, banane.', 17500, false, 4),
  ('restaurant', 'cocktails', 'Hawaï', 'Banane, orange, ananas.', 17500, false, 5),
  ('restaurant', 'cocktails', 'Piña colada', 'Ananas, noix de coco.', 17500, false, 6),
  ('restaurant', 'cocktails', 'Cocktail fruits secs', '', 19500, false, 7),
  ('restaurant', 'cocktails', 'Cocktail Chichkhan', '', 19500, true, 8),
  ('restaurant', 'cocktails', 'Cocktail au choix', '', 19500, false, 9),
  ('restaurant', 'mojitos', 'Virgin mojito', '', 14000, false, 1),
  ('restaurant', 'mojitos', 'Yellow', 'Pêche.', 15500, false, 2),
  ('restaurant', 'mojitos', 'Blue', '', 15500, false, 3),
  ('restaurant', 'mojitos', 'Red', 'Fraise.', 15500, false, 4),
  ('restaurant', 'mojitos', 'Fruits des bois', '', 15500, false, 5),
  ('restaurant', 'mojitos', 'Fruit de la passion', '', 15500, false, 6),
  ('restaurant', 'mojitos', 'Framboise', '', 15500, false, 7),
  ('restaurant', 'mojitos', 'Chichkhan', 'Red Bull.', 22000, true, 8),
  ('restaurant', 'sauces', 'Crème poivron', '', 3500, false, 1),
  ('restaurant', 'sauces', 'Crème champignon', '', 3500, false, 2),
  ('restaurant', 'sauces', 'Gorgonzola', '', 3500, false, 3),
  ('cafe', 'petits-dejeuners', 'Classique', 'Café au choix (express, café crème, capucin ou thé infusion), jus frais (citronnade, fraise ou orange), croissant ou pain au chocolat, eau 0,5 L.', 15500, false, 1),
  ('cafe', 'petits-dejeuners', 'Benna', 'Café ou infusion, smoothie au choix (fraise, banane, ananas ou pêche), brioche perdue Nutella caramel, eau 0,5 L.', 26500, false, 2),
  ('cafe', 'petits-dejeuners', 'Le Gourmand', 'Café ou thé infusion, jus frais, granola bowl (yaourt naturel, granola, fruits de saison, miel), crêpe Nutella, assiette charcuterie, fromage, omelettes et croque-monsieur, salade de fruits, confiture, chamia, beurre, eau 0,5 L.', 29000, false, 3),
  ('cafe', 'petits-dejeuners', 'Le Healthy', 'Café ou infusion, jus au choix (fraise-pomme, ananas-orange ou pomme-concombre-citron), granola bowl (yaourt naturel, fruits frais, graines de chia, miel), toast d’avocat et œuf mollet, eau 0,5 L.', 29500, false, 4),
  ('cafe', 'petits-dejeuners', 'Chichkhan', '2 cafés ou thés, 2 jus frais, 2 viennoiseries, une assiette sucrée (crêpe, pancake ou gaufre Nutella), beurre, confiture, chamia, bsissa, granola bowl, assiette charcuterie (fromages, omelettes et croissant salé), ojja, eau 1 L.', 56500, true, 5),
  ('cafe', 'cafes', 'Expresso', '', 5000, false, 1),
  ('cafe', 'cafes', 'Café crème', '', 6000, false, 2),
  ('cafe', 'cafes', 'Capucin', '', 6500, false, 3),
  ('cafe', 'cafes', 'Cappuccino', '', 7000, false, 4),
  ('cafe', 'cafes', 'Café capsules', '', 7000, false, 5),
  ('cafe', 'cafes', 'Latte', '', 7500, false, 6),
  ('cafe', 'cafes', 'Chocolat chaud', '', 7500, false, 7),
  ('cafe', 'cafes', 'Café turc', '', 8000, false, 8),
  ('cafe', 'cafes', 'Chocolat liégeois', '', 8500, false, 9),
  ('cafe', 'cafes', 'Café gourmand', '', 15000, false, 10),
  ('cafe', 'cafes-glaces', 'Frappuccino caramel', '', 12000, false, 1),
  ('cafe', 'cafes-glaces', 'Café glacé', '', 12500, false, 2),
  ('cafe', 'cafes-glaces', 'Latte glacé caramel', '', 12500, false, 3),
  ('cafe', 'cafes-glaces', 'Café liégeois', '', 12500, false, 4),
  ('cafe', 'cafes-glaces', 'Mocha Nutepistache', '', 13500, false, 5),
  ('cafe', 'thes', 'Thé à la menthe', '', 6000, false, 1),
  ('cafe', 'thes', 'Thé infusion', '', 7000, false, 2),
  ('cafe', 'thes', 'Thé amande', '', 12500, false, 3),
  ('cafe', 'thes', 'Thé pignons', '', 14500, false, 4),
  ('cafe', 'thes', 'Thé gourmand', '', 15000, false, 5),
  ('cafe', 'thes', 'Thé Chichkhan', '', 17000, true, 6),
  ('cafe', 'thes', 'Supplément fruits secs', 'Pignons, amandes, noix de cajou ou noisettes.', 7500, false, 7),
  ('cafe', 'thes', 'Dose Chichkhan', '', 9500, true, 8),
  ('cafe', 'jus', 'Citronnade', '', 12000, false, 1),
  ('cafe', 'jus', 'Orange', '', 12000, false, 2),
  ('cafe', 'jus', 'Citron menthe', '', 13500, false, 3),
  ('cafe', 'jus', 'Fraise', '', 13500, false, 4),
  ('cafe', 'jus', 'Citron pressé', '', 13500, false, 5),
  ('cafe', 'jus', 'Kiwi', '', 15000, false, 6),
  ('cafe', 'jus', 'Pastèque', '', 15000, false, 7),
  ('cafe', 'jus', 'Melon', '', 15000, false, 8),
  ('cafe', 'jus', 'Ananas', '', 15000, false, 9),
  ('cafe', 'jus', 'Pêche', '', 15000, false, 10),
  ('cafe', 'jus', 'Fraise amande', '', 16500, false, 11),
  ('cafe', 'jus', 'Citron amande', '', 16500, false, 12),
  ('cafe', 'cocktails', 'Brazilian lemonade', 'Lait concentré, citronnade.', 14500, false, 1),
  ('cafe', 'cocktails', 'Summer drink', 'Fraise, pastèque, orange, ananas, grenadine.', 15500, false, 2),
  ('cafe', 'cocktails', 'Banane boost', 'Dattes, banane.', 15500, false, 3),
  ('cafe', 'cocktails', 'Banane go Dream', 'Banane, mangue.', 15500, false, 4),
  ('cafe', 'cocktails', 'Arc-en-ciel', 'Banane, kiwi, fraise.', 15500, false, 5),
  ('cafe', 'cocktails', 'Berbère', 'Pêche, menthe, fraise, banane.', 15500, false, 6),
  ('cafe', 'cocktails', 'Piña colada', 'Lait de coco, ananas.', 15500, false, 7),
  ('cafe', 'cocktails', 'Exotique', 'Ananas, mangue, fruit de la passion, kiwi.', 15500, false, 8),
  ('cafe', 'cocktails', 'Chichkhane fruits secs', 'Banane, fruits secs, dattes.', 17500, true, 9),
  ('cafe', 'mojitos', 'Classic', '', 13500, false, 1),
  ('cafe', 'mojitos', 'Fraise', '', 15500, false, 2),
  ('cafe', 'mojitos', 'Bleu', '', 15500, false, 3),
  ('cafe', 'mojitos', 'Framboise', '', 15500, false, 4),
  ('cafe', 'mojitos', 'Kiwi', '', 15500, false, 5),
  ('cafe', 'mojitos', 'Pastèque', '', 15500, false, 6),
  ('cafe', 'mojitos', 'Fruits des bois', '', 15500, false, 7),
  ('cafe', 'mojitos', 'Chichkhan', 'Boisson énergétique, fruit de la passion.', 19500, true, 8),
  ('cafe', 'smoothies', 'Fraise', '', 14500, false, 1),
  ('cafe', 'smoothies', 'Bleu', '', 14500, false, 2),
  ('cafe', 'smoothies', 'Framboise', '', 14500, false, 3),
  ('cafe', 'smoothies', 'Kiwi', '', 14500, false, 4),
  ('cafe', 'smoothies', 'Pastèque', '', 14500, false, 5),
  ('cafe', 'smoothies', 'Fruits des bois', '', 14500, false, 6),
  ('cafe', 'milkshakes', 'Classic', 'Vanille ou fraise.', 10000, false, 1),
  ('cafe', 'milkshakes', 'Nutella', '', 14500, false, 2),
  ('cafe', 'milkshakes', 'Pistache', '', 14500, false, 3),
  ('cafe', 'milkshakes', 'Spéculoos', '', 14500, false, 4),
  ('cafe', 'milkshakes', 'Oreo', '', 14500, false, 5),
  ('cafe', 'milkshakes', 'Kinder', '', 14500, false, 6),
  ('cafe', 'milkshakes', 'Raffaello', '', 14500, false, 7),
  ('cafe', 'milkshakes', 'Snickers', '', 14500, false, 8),
  ('cafe', 'milkshakes', 'Nutella cookie', '', 14500, false, 9),
  ('cafe', 'softs', 'Eau plate 0,5 L', '', 2500, false, 1),
  ('cafe', 'softs', 'Eau plate 1 L', '', 4500, false, 2),
  ('cafe', 'softs', 'Eau gazeuse', '', 4800, false, 3),
  ('cafe', 'softs', 'Soda', '', 5500, false, 4),
  ('cafe', 'softs', 'Oasis', '', 6500, false, 5),
  ('cafe', 'softs', 'Énergétique', '', 10000, false, 6),
  ('cafe', 'glaces', 'Boule de glace', '', 6000, false, 1),
  ('cafe', 'glaces', 'Coupe 3 boules', '', 13500, false, 2),
  ('cafe', 'glaces', 'Sorbet citron', '', 13500, false, 3),
  ('cafe', 'glaces', 'Banane split', '', 17000, false, 4),
  ('cafe', 'glaces', 'Coupe Chichkhane', '', 19000, true, 5),
  ('cafe', 'crepes-sucrees', 'Sucrée', '', 12000, false, 1),
  ('cafe', 'crepes-sucrees', 'Nutella', '', 14000, false, 2),
  ('cafe', 'crepes-sucrees', 'Spéculoos', '', 15000, false, 3),
  ('cafe', 'crepes-sucrees', 'Nutella banane', '', 17000, false, 4),
  ('cafe', 'crepes-sucrees', 'Kinder', '', 17000, false, 5),
  ('cafe', 'crepes-sucrees', 'Pistache', '', 17000, false, 6),
  ('cafe', 'crepes-sucrees', 'Nutella amande', '', 18000, false, 7),
  ('cafe', 'crepes-sucrees', 'Dubaï', '', 19000, false, 8),
  ('cafe', 'brioches', 'Caramel banane', '', 20000, false, 1),
  ('cafe', 'brioches', 'Kinder Nutella', '', 20000, false, 2),
  ('cafe', 'brioches', 'Nutella fruits rouges', '', 23000, false, 3),
  ('cafe', 'desserts', 'Box Le régal de Chichkhan', 'Mini crêpe, mini pancake, mini gaufre, fruits frais. Sauces Nutella, pistache, spéculoos et chocolat blanc.', 39000, true, 1),
  ('cafe', 'desserts', 'Gâteaux & douceurs', 'Tarte aux fruits, amandes, noix ou pistache.', 14000, false, 2),
  ('cafe', 'desserts', 'Cheesecake', '', 14000, false, 3),
  ('cafe', 'desserts', 'Saint-Sébastien', '', 15000, false, 4),
  ('cafe', 'desserts', 'Tiramisu', '', 15000, false, 5),
  ('cafe', 'desserts', 'Tiramisu gourmand', 'Pistache, noisette ou spéculoos.', 19000, false, 6),
  ('cafe', 'desserts', 'Fondant', 'Chocolat ou pistache.', 17000, false, 7),
  ('cafe', 'desserts', 'Assida zgougou', '', 15000, false, 8),
  ('cafe', 'desserts', 'Assiette de fruits', '', 25000, false, 9),
  ('cafe', 'omelettes', 'Thon', '', 12500, false, 1),
  ('cafe', 'omelettes', 'Thon fromage', '', 13500, false, 2),
  ('cafe', 'omelettes', 'Jambon', '', 13500, false, 3),
  ('cafe', 'crepes-salees', 'Jambon fromage', '', 13500, false, 1),
  ('cafe', 'crepes-salees', 'Thon fromage', '', 14500, false, 2),
  ('cafe', 'crepes-salees', 'Tunisienne', 'Thon, harissa, fromage, œuf.', 15500, false, 3),
  ('cafe', 'crepes-salees', 'Norvégienne', 'Saumon, épinards, fromage.', 17500, false, 4),
  ('cafe', 'crepes-salees', 'Burger', 'Fromage, œuf, viande hachée.', 17500, false, 5),
  ('cafe', 'crepes-salees', 'Djerbienne', 'Fromage, poulet, crème.', 17500, false, 6),
  ('cafe', 'burgers', 'Classique', '', 18000, false, 1),
  ('cafe', 'burgers', 'Crispy', '', 18000, false, 2),
  ('cafe', 'burgers', 'Double cheese', '', 22000, false, 3),
  ('cafe', 'burgers', 'Bœuf effiloché', '', 25000, false, 4),
  ('cafe', 'panozzos', 'Panozzo poulet', '', 20000, false, 1),
  ('cafe', 'panozzos', 'Panozzo viande hachée', '', 22000, false, 2),
  ('cafe', 'panozzos', 'Panozzo bœuf effiloché', '', 24000, false, 3),
  ('cafe', 'panozzos', 'Tacos cordon bleu', '', 16000, false, 4),
  ('cafe', 'panozzos', 'Tacos poulet', '', 16000, false, 5),
  ('cafe', 'panozzos', 'Tacos viande hachée', '', 18000, false, 6),
  ('cafe', 'panozzos', 'Box SO Chichkhan', '2 mini panuzzos, tacos, tenders poulet ou cordon bleu, frites ou patates, sauce faite maison.', 42000, true, 7),
  ('cafe', 'pizzas', 'Margherita', 'Sauce tomate, mozzarella, basilic.', 15000, false, 1),
  ('cafe', 'pizzas', 'Végétarienne', 'Sauce tomate, mozzarella, légumes sautés.', 16000, false, 2),
  ('cafe', 'pizzas', 'Roma', 'Sauce blanche, mozzarella, jambon, champignons.', 20000, false, 3),
  ('cafe', 'pizzas', 'Thon', 'Sauce tomate, mozzarella, tomates cerises, thon, olives.', 22000, false, 4),
  ('cafe', 'pizzas', 'Calabraise', 'Sauce blanche, tomates cerises, mozzarella, poulet, oignon, champignons.', 22000, false, 5),
  ('cafe', 'pizzas', 'Diavola', 'Sauce tomate, mozzarella, pepperoni, basilic, tomates cerises.', 22000, false, 6),
  ('cafe', 'pizzas', 'Boursin', 'Sauce blanche, mozzarella, Boursin, viande hachée, oignon.', 25000, false, 7),
  ('cafe', 'pizzas', 'Truffe', 'Sauce blanche, mozzarella, crème de champignon, roquette.', 28000, false, 8),
  ('cafe', 'pizzas', 'Fromages', 'Sauce blanche, mozzarella, crème de champignon, roquette.', 28000, false, 9),
  ('cafe', 'pizzas', 'Pizza SO', 'Sauce blanche, mozzarella, pesto, crevettes, basilic, tomates cerises, noix.', 30000, true, 10),
  ('cafe', 'chichas', 'Al Fakher menthe', '', 18000, false, 1),
  ('cafe', 'chichas', 'Al Fakher pomme', '', 18000, false, 2),
  ('cafe', 'chichas', 'Al Fakher raisin', '', 18000, false, 3),
  ('cafe', 'chichas', 'Al Fakher pomme menthe', '', 18000, false, 4),
  ('cafe', 'chichas', 'Al Fakher raisin menthe', '', 18000, false, 5),
  ('cafe', 'chichas', 'Al Fakher vanille', '', 18000, false, 6),
  ('cafe', 'chichas', 'Chicha Chikh', '', 14000, false, 7),
  ('cafe', 'chichas', 'Chicha Jirak', '', 16000, false, 8),
  ('cafe', 'chichas', 'Supplément tête chicha', '', 10000, false, 9),
  ('cafe', 'chichas', 'Adalya Mia Amore', '', 30000, false, 10),
  ('cafe', 'chichas', 'Adalya Love 66', '', 30000, false, 11),
  ('cafe', 'chichas', 'Adalya Social Smoke', '', 30000, false, 12),
  ('cafe', 'chichas', 'Adalya chewing-gum', '', 30000, false, 13),
  ('cafe', 'chichas', 'Adalya Hawaï', '', 30000, false, 14),
  ('cafe', 'chichas', 'Adalya melon', '', 30000, false, 15),
  ('cafe', 'chichas', 'Adalya pastèque', '', 30000, false, 16),
  ('cafe', 'chichas', 'Adalya menthe sucrée', '', 30000, false, 17)
) as v (venue, category_slug, name, description, price_millimes, is_house, position)
join categories c on c.venue = v.venue::venue and c.slug = v.category_slug;

commit;
